Welcome msg not showing and/or model not loading
TypeError: clean() got an unexpected keyword argument 'styles' error when launching.

From looking at the library the parameter should be css_sanitizer. 

In windows I don't recall seeing the welcome message before when loading the model.

In Linux it was stopping my model from loading all together which is how I noticed the problem. Once updated to the corrected parameter the model now loads in Linux and I see the welcome message a well.